colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts"]

[homepage]
layout = "custom"
showRecent = false

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true