baseURL = "https://dasia373.github.io/"
languageCode = "zh-cn"
title = "工蜂亡命天涯"
theme = "PaperMod"

[params]
  author = "工蜂"
  description = "科研&嵌入式Linux学习记录 24岁是学生"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
